### PR TITLE
Figshare general description

### PR DESCRIPTION
**Pull request by katieroserice**
Added description of Figshare and listed its attractive options for research data management solutions. (I am an intern with rOpenSci.)

### CODE REVIEW

**Comment by cboettig** [comment]
:clap: :rocket: :fireworks:

Nice work getting started with all the markdown and github stuff.  

I think this kind of description is particularly useful for packages listed under the Data Access section here, http://ropensci.org/packages/ where it's apparently not clear precisely what kind of data is being provided by each package/provider.

**Comment by katieroserice** [comment]
Thanks!

For clarification, do you mean you want me edit the descriptions of the
rOpenSci packages under "Data Access" as I did for Figshare and the others?

Let me know!
Katie

**Comment by cboettig** [comment]
yup, send some Pull Requests with edits to the README files, just like you did here, for those packagse

**Comment by katieroserice** [comment]
Okay! And should I edit both the .md and the .Rmd, or just the .Rmd. Scott
told me just to do the .Rmd for simplicity, but I want to make sure that's
okay with you.

**Pull request merged**
